name: "[Test] Build and Test"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: swift package resolve

    - name: Run Tests on iPhone 16 Simulator (iOS 18.0)
      run: |
        xcodebuild test \
          -scheme 'Requestify' \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
