name: "[Test] Build and Test"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:

    - name: Select Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.*'
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Tests on iPhone 16 Simulator (iOS 18.*)
      run: |
        xcodebuild test \
          -scheme "Helping Hand" \
          -project "Helping Hand.xcodeproj" \
          -destination 'platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device' \
          -enableCodeCoverage YES \
          -allowProvisioningUpdates \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
