name: "[Test] Build and Test"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:

    - name: Select Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.*'
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Tests on iPhone 16 Simulator
      run: |
        xcodebuild test \
          -scheme "Helping Hand" \
          -project "Helping Hand.xcodeproj" \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -enableCodeCoverage YES \
          -allowProvisioningUpdates \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -resultBundlePath TestResults
    
    - name: Publish Test Results
      uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
      if: success() || failure()
