name: "[Test] Build and Test"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  test-ios:
    runs-on: macos-latest
    
    steps:

    - name: Select Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.*'
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
          -scheme "Helping Hand" \
          -project "Helping Hand.xcodeproj" \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -resultBundlePath BuildResults
    
    - name: Run Tests Without Building
      run: |
        xcodebuild test-without-building \
          -scheme "Helping Hand" \
          -project "Helping Hand.xcodeproj" \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -resultBundlePath TestResults
    
    - name: xcresulttool (replace with official version when Xcode 16 support is merged)
      uses: slidoapp/xcresulttool@v3.1.0
      with:
        path: TestResults.xcresult
        token: ${{ github.token }}
        title: Xcode test results
        show-passed-tests: true
        show-code-coverage: true
        upload-bundles: always
      if: success() || failure()
