name: Dummy DocC Structure Example

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  show-structure:
    runs-on: macos-latest

    steps:
      - name: Create Dummy DocC Structure
        run: |
          set -x # Enable shell debugging

          FINAL_DOCS_DIR="docs"
          DUMMY_MODULE_NAME="MyDummyModule" # Replace with your actual module name if known

          echo "--- Creating dummy DocC structure ---"
          rm -rf "$FINAL_DOCS_DIR"
          mkdir -p "$FINAL_DOCS_DIR/documentation/$DUMMY_MODULE_NAME"
          mkdir -p "$FINAL_DOCS_DIR/css"
          mkdir -p "$FINAL_DOCS_DIR/js"

          # Create dummy index.html files
          echo "<!DOCTYPE html><html><body><h1>Dummy Root Index</h1><script>window.location.href = window.location.origin + '/MyRepoName/documentation/$DUMMY_MODULE_NAME/index.html';</script></body></html>" > "$FINAL_DOCS_DIR/index.html"
          echo "<!DOCTYPE html><html><body><h1>Dummy DocC Module Index for $DUMMY_MODULE_NAME</h1></body></html>" > "$FINAL_DOCS_DIR/documentation/$DUMMY_MODULE_NAME/index.html"
          echo "body { background-color: #f0f0f0; }" > "$FINAL_DOCS_DIR/css/style.css"
          echo "console.log('Dummy JS loaded');" > "$FINAL_DOCS_DIR/js/script.js"
          echo "Some other asset content" > "$FINAL_DOCS_DIR/documentation/$DUMMY_MODULE_NAME/data/documentation.json"
          echo "Another asset" > "$FINAL_DOCS_DIR/images/logo.png"

          echo "--- Listing contents of the 'docs' directory ---"
          ls -R "$FINAL_DOCS_DIR"
